// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu6eYWKzJESssB3Zvo1xH2t3MWGUVrHQ0',
    appId: '1:545064127049:web:2b711bfa6dc7af90a18d98',
    messagingSenderId: '545064127049',
    projectId: 'aup-software',
    authDomain: 'aup-software.firebaseapp.com',
    storageBucket: 'aup-software.appspot.com',
    measurementId: 'G-X3NH5QHG3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9rnagHQM84ISPc6GzUIxjQK3bEosv9Qo',
    appId: '1:545064127049:android:4b5fc3776965a648a18d98',
    messagingSenderId: '545064127049',
    projectId: 'aup-software',
    storageBucket: 'aup-software.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcXIetvIShIi_2xgzEqzwz-CoxOG_pbbg',
    appId: '1:545064127049:ios:5cdedb1a3d4d61dca18d98',
    messagingSenderId: '545064127049',
    projectId: 'aup-software',
    storageBucket: 'aup-software.appspot.com',
    iosBundleId: 'com.example.ricardoPeres',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcXIetvIShIi_2xgzEqzwz-CoxOG_pbbg',
    appId: '1:545064127049:ios:5cdedb1a3d4d61dca18d98',
    messagingSenderId: '545064127049',
    projectId: 'aup-software',
    storageBucket: 'aup-software.appspot.com',
    iosBundleId: 'com.example.ricardoPeres',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu6eYWKzJESssB3Zvo1xH2t3MWGUVrHQ0',
    appId: '1:545064127049:web:6575d2f357042d7aa18d98',
    messagingSenderId: '545064127049',
    projectId: 'aup-software',
    authDomain: 'aup-software.firebaseapp.com',
    storageBucket: 'aup-software.appspot.com',
    measurementId: 'G-H2C5BX2NS4',
  );
}
