class Arcanos {
  static Map descricao() {
    return {
      "11":
          "O arcano 11 a força significa que neste período você vai despertar o lado espiritual é muito provavelmente engajando-se em estudos da espiritualidade muitos se convertem outros descobrem a religião e o poder espiritual agora toma conta da força da vibração o despertar espiritual neste período é inevitável onde as forças da espiritualidade transforma a sua mente teu despertar espiritual te ajudará a triunfar sobre o ódio período de Vitória período onde a situação também de conflito com você mesmo estarás administrando bem suas emoções neste período representando disciplina e dominando a situação é o período da força da mente domínio sobre o ambiente todo o movimento espiritual atuante o espiritual vencendo o poder material",
      "12":
          "Arcano 12 o enforcado será chamado para situações de sacrifícios se encontrará muitas vezes Independência na espera e às vezes trazendo até um sentimento de impotência afinal vocês também estará engajado em ajudar e assim sacrificar em prol dos outros e de você mesmo e com isso um despertar para os estudos principalmente nas áreas muitas vezes místicas buscando respostas será uma transformação da sua personalidade através da renúncia e do sacrifício muitas vezes no enforcado laços serão criados dependências também e a espera",
      "13":
          "Arcano 13 a morte e o renascimento você estará vivenciando um período onde haverá uma transformação profunda sente que uma parte sua está morrendo para dar lugar às outras partes às novas partes, novos valores novas motivações, novas formas de pensar, agir e sentir esse período será inevitável o teu renascimento deverás abrir mão de parte sua que não é mais fazer os fechamentos e se permitir o renascimento se haverá sofrimento ou não é a sua capacidade de liberar e renascer a vida exigirá de você renovações em todos os setores da vida no trabalho no amor, no lazer, na saúde nos relacionamentos pensamentos em geral.",
      "14":
          "Arcano 14, a temperança. Neste período, haverá uma grande necessidade de trabalhar seus sentimentos em relação às pessoas do seu convívio. Naturalmente, uma angústia. Naturalmente, também, sentimento de necessidade de mudar. Uma necessidade de trabalhar suas emoções nas relações, mas saiba que estarás fazendo boas administrações nos negócios e conseguindo êxito.",
      "15":
          "Arcano 15, o diabo. Período dos excessos, muitas vezes ocasionando algumas enfermidades. Período onde você se envolverá com os níveis mais profundos. Os níveis mais profundos da sua mente, encontrarás com o que está reprimido, oculto, na base da sua personalidade, muitas vezes trazendo uma sensação de culpa, pecado. Deverás cortar em excesso as suas impulsões, permanecerá muitas vezes com excesso de pensamento e muita tentação. Sexualidade sua aflorará os relacionamentos, encontrará em conflito, muitas vezes em função de algumas traições. \n\nE encontrarás também em uma fase onde deverás ver em que nível da sua mente você está indo e cortar pela raiz os excessos. O período do diabo. Pede controle dos impulsos, poderá ser atraído para acidentes também. Ficar atento com o seu descontentamento e trabalhar. Será um teste, são os períodos de provações. Lados ocultos, medos. Cuidado com os apegos.",
      "16":
          "Arcano 16,  A torre. Todo nesse período que não estiver sólido, estarás em destruição. Você vai experimentar toda uma reconstrução neste período. Todas as estruturas, as velhas ideias, acusações falsas, opressão, estará com você neste período. A torre vem de cá a um modo brusco de viver, muitas vezes por algum acontecimento ou fatalidade e vai depender de como você tem reagido diante das situações. Tudo aquilo que no passado não estava sólido vem à tona, destruição seguido de renovação. \n\nNeste momento, deverás calcular perfeitamente tudo em sua vida e ressignificar e reestruturar. A torre pede. Esses dias de desapego e aceitação. ",
      "17":
          "ARCANO 17 A ESTRELA Neste período você brilha, você encontra inspirado, um sentimento de esperança. É um grande período de uma ajuda, e ajudas também desinteressadas, espirituais. Você começa a desenvolver dons mentais, loucos e caros. mentais e espirituais e começa a renascer em você a alegria e o amor, mesmo que meio às atribulações, estarás você conectado e desenvolvendo seu otimismo diante das situações, perceberá reinícios e caminhos sendo reabertos, seus projetos serão favoráveis nesse período.",
      "18":
          "tudo que está escondido vem à tona, você atravessa um período de intuição, muitas vezes viagem astral, se pegando com incertezas, as suas faculdades psíquicas estão em desenvolvimento neste período, os cuidados com os inimigos ocultos, os cuidados com os inimigos ocultos, os cuidados com os inimigos ocultos, os cuidados com a inveja, enfrentará o mundo subconsciente dos sonhos, neste período é comum de ocorrer intrigas, fofocas vão surgindo e todo um período da viagem astral. ",
      "19":
          "período maravilhoso, onde significará uma grande mudança, vida bem vivida, trabalhos serão bem feitos, um grande despertar e grandes renovações, assuntos legais favoráveis, grande período de acumulação no plano espiritual, haverá clareza na sua mente e confiança renovada, você neste período está brilhando, com muita sabedoria, generosidade faz parte do período, confiança de caráter, saúde e bem-estar. , período de confiança, saúde e bem-estar.",
      "21":
          "O mundo, liberdade, solução, trabalhos bem feitos, triunfo sobre tudo o que você empreende, é um grande período de realizações e sucesso, momento onde você consegue alcançar aquilo que você busca, você atinge o ideal, representará também o poder da mente, solução de todas as questões, poderes mentais despertando, sucesso, viagem em plenitude. período de confiança, saúde e bem-estar. \n\nPeríodo de confiança, saúde e bem-estar. Atinge o ideal, representará também o poder da mente, solução de todas as questões, poderes mentais despertando, sucesso, viagem em plenitude.",
      "22":
          "Neste período você se encontrará em uma decisão importante, se encontrará diante de uma escolha, e essa escolha vai ser decidida com cuidado e com coragem. Sobretudo, deverá atender a sua própria intuição, porque haverá um novo capítulo de vida. Haverá um grande desejo de se saltar no desconhecido.\n\nRepresentará todo um movimento espiritual de espontaneidade, espiritual atuando no material. ",
      "23":
          "Aparecerá agora na sua personalidade uma nova ideia. Sua mente estará gerando ideias novas, com grande habilidade de liderança, bondade, honestidade, é o símbolo também do poder adquirido pelo mérito e pelo trabalho. Você colhendo o que plantou, estarás assegurado nos seus cargos, você estará bem colocado e protegido. Representará autoconfiança, grande motivação, espírito empreendedor, sabedoria e convicção. As amizades aumentam e o respeito impera.",
      "24":
          "Será o símbolo da posição elevada. Você se elevando em sua posição, com grande força da mente e da imaginação. Constante e objetivo. Neste momento, você recebe também proteção e aconchego. Também dá proteção e aconchego. Representando então, agora sim, ação, criatividade. Você atraente e inteligente. E crescendo na sua atividade com muito amor pela vida. ",
      "25":
          "Neste período, será um período de diserção. Partida, mudanças. Abandonando uma fase, iniciando uma nova fase. É uma situação muito importante. E também, símbolo dos altos empregos. Promoção. Haverá então, a luta para conquistar a posição. E o poder será adquirido por essas lutas. E você desenvolvendo qualidades em você mesmo. Qualidades mais exuberantes. Mais ousadia, aventuras, e também mudança de residência, de cidade, ou de modo de vida.",
      "26":
          "Significará curiosidade. Você entusiasmado e audacioso. Neste momento, sempre uma sensação de insatisfação lá no fundo. Mas não vai ser uma mudança. Uma mudança radical em função disso. Carregarás apenas uma certa insatisfação de fundo. Mas é a mudança, chegada de boas notícias, ação imediata, entusiasmo. E o período onde você mais terá a possibilidade de viajar. ",
      "27":
          "Tensão. Fardo pesado. Se sentindo sobrecarregado. E as responsabilidades. Muitas responsabilidades neste período. Você se vendo com excessos de responsabilidades. Tensão e muitas vezes preocupação. Alguns desentendimentos farão parte do período. Pode ser que venham traições, hipocrisias, falsidades. E você com necessidade o tempo todo de mudar de fase.",
      "28":
          "O sucesso vai depender de muita prudência neste período. Seus empreendimentos estarão mais misteriosos. As viagens podem ser perigosas. Haverá muitos atrasos e suspensão. Adiamento. Demora. Surpresas. Atitude defensiva deverá ter. Medo de se machucar. Vai levando a uma situação de desconfiança neste período. Um período um pouco mais tenso também.",
      "29":
          "Vai ser um período da fluidez dos impulsos criativos. E o sucesso agora sim na sua meta estará ao seu alcance. Será um período de ação. Depois de muita espera. E as suas ideias vão te levar para campo, agricultura, bens imóveis, divertimento. Viagens por causa de dinheiro e grandes negócios. E você encontrando com a paz e alegria. Felicidade certa. E esse momento agora sim você vai equilibrando o teu orçamento.",
      "31":
          "Período de sucesso nos empreendimentos Seus esforços sendo compensados Vitória, reconhecimento Onde estarás garantido no emprego Onde também estará garantido nos seus empreendimentos Se você estiver para ser empregado, trabalhar Acontecerá neste período Se você estiver com espírito de empreendedor Empreenderá Terá o seu empreendimento E terá grande sucesso.",
      "32":
          "Significará que neste período Haverá grandes êxitos Deverás então manter focado Pois haverá disputas Uma certa inquietude Mas haverá grandes sucessos Um grande espírito esportivo Período de grande poder de competição E também respeito Espírito de competição Disputas sadias Espírito esportivo E grandes confrontos de ideia",
      "33":
          "Neste período significará Grandes recompensas Pelos seus esforços empreendidos Realização do sucesso esperado Empresas sérias e estáveis Alianças, contratos, êxitos E você desfrutando dos grandes e bons resultados do seu trabalho Se encontrará em ambientes agradáveis Com boa comunicação e sociabilidade.",
      "34":
          "Haverá neste período Começo de êxito no seu trabalho Em seus empreendimentos Ou em tudo o que empreender Grande espírito de criatividade Inovação, invenção Receberá ajuda de alguém de sua confiança E os negócios prosperarão Representará toda a energia de uniões E a união cria grande força Você criativo Atraindo associações para você A visão de longo alcance ",
      "35":
          "Significará equilíbrio Grande capacidade de intuição Você se percebe Formulando um novo projeto Motivado Grandes ideias Novas ideias Coisas que permanecem Na sua vida a partir de agora Todo esse objetivo Será fundamental Para você Para a permanência Dos seus planos futuros Mas Guardará sempre Segredos e mistérios Deste futuro brilhante Representará o grande poder Que se manifestará como Cooperação e ajuda \n\nPeríodo de muitas assistências Tanto você para com o outro E do outro para com você Perceberá lá no fundo Sempre uma indecisão Ficará em dúvida também Sobre Dividir para multiplicar E deverá dividir Para multiplicar.",
      "36":
          "Grande força de ideia Período de grande criatividade E você vendo novos horizontes Você querendo se arriscar Em novos empreendimentos E você querendo se arriscar Além desse período Geralmente haverá nascimento De criança Se não sua No entorno Período de grande fertilidade.",
      "37":
          "O controle A terapia O terapeuta Você experimenta um aspecto novo Da sua própria personalidade Você perceberá Buscando o conselheiro O terapeuta O psicólogo E você também com essa energia do conselho, pois agora você é um bom ouvinte e você também amadurece mentalmente e consegue com você, você mesmo consegue dar as suas palavras de carinho, amor, há muita procura para os seus conselhos nesse período. Perceberá o sentimento das pessoas, grande empatia, força espiritual da alma, generosidade, honestidade e alta ajuda prevalecerá nesse período com muita intensidade.",
      "38":
          "É o grande período da maturidade, da confiança e você encontrando com seus sentimentos mais profundos, anunciará a justiça, é um período muito equilibrado, de grande maturidade emocional.",
      "39":
          "agora sim você experimentará a incrível mágica do amor, paixão, conexão com a paixão, indicará uma proposta de casamento ao mesmo momento que você se apaixona. Haverá também nesse período propostas de trabalho e você envolvendo com os ideais mais elevados. Chegada de novas amizades, reconciliação, grande comemoração, o amor. Raquel. ",
      "41":
          "Agora sim, o grande período da felicidade desejada é um período de muito contentamento e harmonia nos domínios do coração. Estarás em realização dos seus sonhos, das suas metas, das suas esperanças. Um período todo de vida feliz, muitas simpatias. Se encontrará a nível emocional de muito sentimento bom, de sucesso. Felicidade familiar compartilhada. Você com boa reputação no lar e um lar feliz. Sociedades levando a sua vida feliz. Se encontrará com o sentimento de realização. ",
      "42":
          "Neste período, seus desejos serão realizados. Um período de satisfação, alegria e, principalmente, realização dos seus sonhos, dos seus projetos. Haverá um aumento financeiro, honras, glória, boa reputação, período de vitória, êxito, prosperidade, lealdade, franqueza, representará também a felicidade e o bem-estar, segurança material e você com alegria de viver. ",
      "43":
          "Haverá, neste período, uma necessidade de buscar um sentido para a sua relação amorosa. Necessidade de despertar ou desistir da relação. Pois haverá um excessivo interesse pelos prazeres que vão atrair para você escândalos amorosos. Podendo trazer também paixão. Ou mesmo divórcio. Mas é um período. Se estiver no relacionamento ou casamento, haverá conflitos e um mau relacionamento. Um mau casamento. Pois representa a sedução fora do padrão. Então, haverá partida difícil. Porque você não percebeu. Ou a tempo. Seu papel na relação.",
      "44":
          "Período de muitos pensamentos e conflitos. Uma situação emocional, a qual você se vê com várias possibilidades e se colocando em conflito. Você tendo que ser mais realista. Você tendo que ser mais realista. Buscar ser mais realista. Para que o veja que a relação ele é tão boa. pois haverá uma sabotagem ou autossabotagem. Representará também algumas ilusões, megalomania, fantasias, êxitos de pouco valor, fugindo da realidade. Um momento de defesa onde haverá sabotagem.",
      "45":
          "Seus desejos do passado agora serão realizados, pois todo o passado te abraça. Se encontrará com pensamentos no passado, lembranças do passado, pessoas do passado, e muitas vezes o amor antigo do passado. E também o seu sonho do passado será realizado neste futuro próximo. Será você feliz, se entregando a momentos felizes. Mas a mente está toda voltada para o passado, e a energia do passado te abraçando neste momento. Normalmente, farás recordações, trazendo recordações felizes, conseguindo paz interior, e momento também de energia de aceitação do passado. Sonhos do passado.",
      "46":
          "Neste período, haverá final de uma relação ou amizade. Ou mesmo sociedade. Remorso. Algo não dará certo. Na maioria das vezes, uma possível traição. E assim, poderás, se encontrar em tristeza e arrependimento. Período onde haverá uma separação num relacionamento. Muitas vezes, pode não significar um rompimento definitivo, pois laços já foram criados. Representa lamentações, prazeres obscuros, despedida dolorosa, amargura, tristeza profunda, sentimento, às vezes, até de fracasso. ",
      "47":
          "Neste período, haverá alguns aborrecimentos, certa insatisfação, tristeza profunda, algumas vezes, depressão. Pois haverá muita inconstância e desequilíbrio dos sentimentos, te trazendo uma falta de motivação, uma certa apatia. Acharás, que, forças, uma válvula de escape, buscando prazeres excessivos. Mas que o resultado será cansaço, arrependimento. Pois vai querer esconder algo que está relacionado às suas emoções, mas o período pede moderação nas relações e tudo o que tem a ver com as emoções. ",
      "48":
          "Agora sim, êxito Haverá neste período o começo de um novo estilo de vida E também de um relacionamento Ou um novo começo lindo no relacionamento Período também traz o nascimento de uma criança E situações promissoras de realização emocional É você em situações onde haverá o início Dos níveis mais profundos das experiências do coração O amor Novas descobertas Período que representando a vida Período que representando alegrias, diversão, celebração, sucesso Muitos casam neste período e têm filhos.",
      "49":
          "Haverás Celebração Amizade Amor. É o início de um relacionamento ou mesmo um casamento Energia toda de reconciliação em todos os setores. Sugerindo também Encontro Comerciais Acordos comerciais E uma relação de um grande poder de atração entre duas pessoas Por isto também Neste período Muitas amizades União afetiva e casamento",
      "51":
          "Todo um período de grande maturidade e sabedoria Você enxergando agora além Absorvendo conhecimento Com a sua vida Como nunca antes Se encontrando confiante E um conselheiro confiável E você buscando também o conselho Muitos encontram em momentos terapêuticos ou de autoajuda Aconselhando e sendo aconselhado Encontrando dentro de si Dons outros de liderança Arrojo Inspiração e confiança Pronto para desenvolver novos projetos e motivado Para desenvolver novos projetos e motivado Por isso Representando um pensamento mais organizado Com ideias mais claras Mais objetividade Espiritualidade Versatilidade Muita confiança e autoridade.",
      "52":
          "Momento que você vai confrontar com a sua própria fé Esses confrontos Esses questionamentos Só irão contribuir para aperfeiçoar a sua consciência Haverá mais qualidade de vida após esses confrontos internos Será preciso também Você conseguir enxergar Onde você está criando os problemas para si mesmo Porque vai exigir você Perfeição De ti e dos outros Representando Todo um período de grandes questionamentos E você muito associado no momento Um conselho Pegue a opinião de pessoas de fora Pois você está dentro das emoções E não está conseguindo ver com razão Conselheiros em volta É sempre bom neste momento",
      "53":
          "Prepare-se Haverá grandes mudanças repentinas na sua vida Para quebrar os antigos Padrões existentes Nada permanece como antes Tua rotina vai mudar Teu modo de viver vai mudar Situações inesperadas vão acontecer Tendência para rompimento fascina Haverá também Novas ideias Em função dessa quebra de padrão Novos projetos E muito para Quebrar as antigas formas de pensamento E muito para quebrar as antigas formas de pensamento E muito para quebrar as antigas formas de pensamento E muito para quebrar as antigas formas de pensamento representará todo um pensamento organizado agora. Deverás você dançar conforme a música. Qualquer resistência nesse momento trará sofrimento. Quebra de padrão. ",
      "54":
          "Este periodo vai ser o momento que você vai confrontar muito, com muita curiosidade, vigilante, fofoca e mexerico. Você está disposto a fazer isso e também as pessoas param com você. Pode ser que você se torne também vítima de intriga dos outros e, tendendo a se envolver em pequenas disputas, todo um período que vai representar vigilância, espionagem e, muitas vezes, discórdia, conflitos. ",
      "55":
          "Todo um período de finalização difícil, muitas vezes dolorosa, mas o problema vai ser encarado de frente com honestidade. E o seu futuro terá menos conflito, pois vai aprender com a lição. A situação econômica e a saúde tenderá a melhorar neste período, mas, por parte, representará alguma desolação, algum momento um pouco insuportável e um pedido de ajuda deverá ser atendido. E você finalizando uma ideia e um processo em uma situação que já se esgotou há mais tempo. ",
      "56":
          "Todo um período de muita ansiedade e dúvidas em relação ao futuro. Você tendo que buscar dentro de você seus conflitos internos, identificando a tua culpa e trabalhando. Não se deixe escravizar pela emoção, porque ela pode ser uma coisa que não é. Ela pode te deixar paralisado, triste, preocupado, abatido e trazendo insônia com sentimento de impotência. ",
      "57":
          "Uma decisão se faz necessária nesse período. Você se pegando indeciso, com força paralisada, impossibilidade de ação, até mesmo confusão mental. Observar se está na sua auto-sabotagem, pois haverá dificuldades e você com medo das consequências. ",
      "58":
          "Este sim é o momento de agir com muita diplomacia. Deverá ter um grande controle emocional, evitando os confrontos diretos, pois os seus planos não darão certo como esperava. Mas a vida, assim, exige. Seus planos não vão dar resultado ou não estão dando. Seus esforços parecerão inúteis. Confrontará com algumas falsidades, impostura e você tendo que agir pensando mais lá na frente, com muita cautela, você se vendo preso entre razão e emoção. Momento de não tomar grandes decisões, sem precisar de decisões.",
      "59":
          "Este período agora, você já libera toda a sua preocupação, que foi provocada anteriormente, possivelmente. É um período onde transitará por uma sensação mais serena, pois, você já procura os novos objetivos, e você tem progresso e o sucesso merecido neste período. Haverão viagens, novas experiências, novas transformações excitantes. É um terreno novo, mudança, e você aprendendo muito sobre a ciência mental, pois agora você consegue dissociar e ver o problema de fora, de outra perspectiva. ",
      "61":
          "Haverás, neste período, introspecção, introversão, você buscando o silêncio, com necessidade de recuperar as suas forças, a situação tendendo a melhorar. Todo este período, vai representar você buscando a paz mental, você dando uma trégua, um tempo, querendo fazer retiro para recuperar as suas forças, e você esperando o momento certo. Muitas vezes, questionar a dor e questionando dos sacrifícios que foram feitos anteriormente. Momento bom para meditar. ",
      "62":
          "Neste período haverá conflito, dor, separação , brigas levando a grande desgosto e você com dificuldade de perdoar. Mas perdoe, busque trabalhar o perdão, pois é um período que haverá dor e sofrimento, sentimentos feridos, tristeza.",
      "63":
          "Haverá um estado de tensão, e você na recusa, indeciso, indeciso, indecisão na hora de definir opções. Um período de dilema, de análise, desequilíbrio mental. É melhor que não decida nada neste momento em função da sua mente e das suas emoções em desequilíbrio. Representará um pouco de estagnação e você buscando paz ",
      "64":
          "Haverá neste momento um conflito, mas o conflito interno. Em função desse conflito interno, desse questionamento, haverá um despertar espiritual, um despertar mental, trazendo uma grande mudança na sua vida. É o poder da mente e da razão. Agora sim, a grande capacidade para triunfar, compreensão, prontidão. A hora da chegada. Haverá então uma nova maneira de pensar e usar a mente.",
      "65":
          "É neste período que você começa a aceitar os grandes desafios materiais da vida. Vai canalizar a confiança e vai se aperfeiçoar neste processo. Então, haverá sim realização material da sua pessoa. Estarás em boa posição nos negócios, pois a sua inteligência masculina para o sucesso haverá. Também, grande sensação auditiva, você mais sólido, estável e com muito tino comercial. É todo um período que você será o rei de todos os recursos, o grande investidor. ",
      "66":
          "Neste momento, você vai voltar mais para as situações do próprio corpo, para a saúde, dando valor para o autocorpo, buscando a sua autoestima. Também promovendo mais sensualidade E voltada para os prazeres do corpo, e que preservam também a saúde, enriquecendo sua vida. Você estabelece condições de vidas mais seguras e estáveis, mudanças de rotina, se nutrindo melhor, com administração mais apropriada, se encontrará também economizando dinheiro e esforços, representa todo um cuidado para contigo e sua inteligência feminina atuando no plano criativo. Dinheiro, fidelidade, fertilidade nesse período, senso familiar, competência no rumo certo, você mimando os baixinhos, cuidado, nutrição e proteção é o que prevalecerá nesse período. ",
      "67":
          "Nesse período você vai desenvolver uma dimensão nova da sua personalidade, você aceitando as tarefas que são dadas a você com serenidade e firmeza, com caráter, com muita dedicação e firmeza nas suas atitudes. Decisão e ação, ação firme, motivada, com motivação constante, tendo êxito e conquistando. Se encontrarás em paz e novas ideias que vão gerar ação e dinheiro. Prepare-se para recebimento de propostas e ofertas, e você cautelosa ou cauteloso e observador. Você agora sabe o que deseja. ",
      "68":
          "Nesse período você já está acumulando energia para utilizar para realizar o novo projeto material. Projetos estes que também vão envolver com o corpo, saúde, necessidades do corpo e vão aparecer quantias de dinheiro que devem ser poupadas nesse período ao invés de ser gastas inutilmente. Saiba investir. Haverá um poupada. Um passatempo que você agrega na sua profissão, um novo conhecimento, uma especialização, algo assim. Pois, pelo fato de você ter tido essa nova ideia, com essa nova visão, as oportunidades irão surgir neste período. Representará também propostas valiosas e concretas, grandes oportunidades no plano material. E você, observador, estudando o caso. ",
      "69":
          "Grande período de realização artística. Ou realização profissional. É você perpetuando coisas boas. Agora você está na posse do segredo. Você está na posse da riqueza, tendo plenitude. Por isso, se encontrará com muita satisfação e segurança. E vai realizar algo permanente que vai ser passado adiante. Então, neste período, a sua situação econômica prospera. E muitas vezes surge um partilhamento de herança ou uma nova aquisição. ",
      "71":
          "Neste momento, você é o grande aprendiz. Com muita vontade de estudar e aprender. Se encontrará satisfeito, empolgado e empenhado em desenvolver o seu novo ofício. Pois, neste período, você descobre o seu talento oculto. E este talento deve ser trabalhado e desenvolvido. Pode se transformar em uma profissão altamente lucrativa. Se for um passatempo, faça valer. Encare, pois pode ser que vire uma profissão muito promissora. Pois você agora está no aprendizado. Você é o grande aprendiz. Então, sua energia vai toda sendo dirigida para os aprendizados. Haverá práticas. Repetição. E as básicas serão confirmadas. ",
      "72":
          "É o momento de grande tomada de decisão. Haverá cautela? Você com essa energia para este novo projeto. E fortuna será adquirida pelo trabalho pessoal. Representará todo um período de paciência. De ser devagar e sempre.\n\nE você amadurecendo e escolhendo o momento certo para tomar a melhor decisão. Mas, haverá também dúvidas se você investe mais ou se contenta com o que já colheu. ",
      "73":
          "Todo um período de bondade, generosidade sua e dos outros. Você oferecendo sua generosidade e recebendo também. Tanto financeira como pessoal. Período que você recupera sua confiança e fé na vida. Coisas boas e possível ascensão. E você desfrutando dos bons trabalhos do seu resultado. Você desfrutando dos bons resultados do seu trabalho. Representa surpresas agradáveis, presentes, filantropia, generosidade. Disposição para ser ajudado. E ajudar. Compreensão. Sucesso.",
      "74":
          "Prepare-se para este período pelas dificuldades financeiras que ocorrerão. Haverão algumas perdas, podendo tirar a sua confiança. Você pode perder a confiança nesse período. É importante que você reaja positivamente. Não se deixe levar pelas emoções. Afinal, tudo passa. Tudo é fase e passageiro. Período que você vai ter que aprender a lidar com obstáculos e crises. Queda financeira. Muitas vezes as pessoas enfrentam desemprego. E alguns uma ruína econômica. Trazendo a grande preocupação e sentimento de impotência. ",
      "75":
          "Neste período. Estará favorável. E haverá uma aquisição ou herança. Capacidade de trabalho. Muita energia para trabalhar. E atraindo acúmulo de posses. O poder econômico e a prosperidade te alcançam. E você começa agora sim a estabilizar os seus recursos para conservar. ",
      "76":
          "Grande período de sucesso nos seus empreendimentos o teu projeto agora começa a dar lucro mesmo a sua obra artística ou profissional vai atingir o sucesso, o prêmio e o reconhecimento do trabalho e do seu talento haverás fortuna por empresas habitualmente dirigidas nesse período você está um gênio no trabalho representará o trabalho material construção prepare-se para o progresso para os holofotes pois sucesso pelo trabalho em equipe estará com você ",
      "77":
          "Haverá nesse período uma disponibilidade de um recurso financeiro e também de energia para realizar os novos projetos será necessário que você esteja aplicar o seu capital e assumir os riscos ao invés de economizar para possibilidades futuras pois este momento sim é favorável principalmente para vocês que sabem lidar com dinheiro fortuna será dividida probabilidade de ações produtivas representando trocas harmoniosas grande adaptação para lidar bem com os recursos conquistados novas adaptações ",
      "78":
          "Período onde a possibilidade da realização material já está ao seu alcance você com muita disposição para executar os seus trabalhos e haverá agora sim a prosperidade suas aventuras serão muito bem sucedidas dinheiro também surgirá de outras fontes dinheiro também surgirá de outras fontes podendo ser herança, jogo alguma aquisição haverá uma grande oportunidade para concretizar dentro do plano material e da riqueza novas habilidades e também o despertar de novos talentos",
      "79":
          "Período que haverá um reinício reinício de novas atividades nova vida, um novo momento de vida período da grande reconstrução",
      "81":
          "poderá haver problemas com justiça lei causa efeito o que se planta nesse período visilmente você colhe toda a lei de causa e efeito estarás neste período ",
      "82":
          "você estará servindo de escada para os outros voluntariamente e involuntariamente mas estarás com disposição para isso afinal depois você é ajudado também depois você é ajudado também período onde você passa seus conhecimentos e dar o seu suporte",
      "83":
          "você estará associada ou associado com o intelectual ou cultural e progredindo você estará associada ou associado com o intelectual ou cultural e progredindo estudos, academia, cursos, associações intelectuais, etc. grupo, arte, cultura, progresso ",
      "84":
          "você se encontra trabalhando com o povo e para o povo buscando também a parte filantrópica e humanitária trabalho com muitas pessoas grupos",
      "85":
          "neste período haverá um afastamento social em profundidade isso vai causar perda temporária de bens ou da própria vida muitas vezes perde-se parentes existe acidentes ficar sempre atento e estabilizar suas bases ficar sempre atento e estabilizar suas bases não se arriscar não ter riscos é importante uma necessidade de se afastar. ",
      "86":
          "Agora sim significará a vitória sobre aquilo que você já estava tentando há muito tempo. Depois de muita luta e determinação chegou o grande momento da vitória. Arcano 87. Equivale ao diabo. ",
      "87": "Arcano 87. Equivale ao diabo. ",
      "88": "Arcano 88. Significará a torre. ",
      "89":
          "Mérito não reconhecido. Sentimento de frustração. Neste período é importante não criar tanta expectativa em relação aos seus planos e nas pessoas. Tua estrela para de brilhar. Não brilha mais tanto quanto antes durante este período. Reconheça, aceite e aprenda.",
      "91": "Haverás um sentimento de solidão. Vontade de ficar só. ",
      "92":
          "Haverás uma união tardia ou associação com grupos de pessoas. Estudos. ",
      "93":
          "Arcano Sua menteuma grande sabedoria e dos e bons e grandes resultados. Haverás ótimos resultados neste período. Em tudo.",
      "94": "Significa solidão velhice ou morte de uma pessoa. ",
      "95":
          "Você agora será reconhecido intelectualmente. Muitas vezes significa prêmio, reconhecimento, status. ",
      "96":
          "Vai significar neste período amores secretos que vão causar graves problemas. Também a chegada de novas provações. Muitas vezes triângulos amorosos.Cuidado para não cair no conto do vigalho. Haverá um afloramento sexual e os sete pecados capitais no entorno. Período que você deverá trabalhar os seus excessos. Risco de contaminação, confusão amorosa, cegueira amorosa, prazeres da carne. Cair na tentação. Período extremamente material e sexual.",
      "97":
          "significa uma decisão difícil que vai ser tomada. Ou então, a solidão muito esperada que se concretiza. Muitas vezes, temos perdas nesse período. ",
      "98":
          "Agora você estará em um alto cargo com grande influência. Ou você sobe de cargo. O teu reconhecimento se torna maior. ",
      "99":
          "significa período onde haverá entrada de muito dinheiro. Ou mais dinheiro que todas as vezes. Que toda temporada. Pode apresentar riqueza material.",
    };
  }
}
