class Ciclo {
  static description() {
    return {
      "1":
          """A falta do pai não se resume apenas à sua ausência física. É a forma como a criança lida emocionalmente com a situação familiar em que está inserida. Durante a adolescência, esses sentimentos podem se manifestar em inseguranças, rebeldias e dificuldades de relacionamento. Já na juventude, a superação desses obstáculos pode vir através do desenvolvimento saudável da individualidade, mas também é possível que a pessoa permaneça ligada ao passado, enfrentando dificuldades no convívio social e no avanço profissional. Em resumo, o primeiro ciclo de vida favorece a iniciativa, independência e autoridade para alcançar as ambições pessoais, porém, traz consigo uma certa dose de solidão e expectativas frustradas em relação ao apoio dos outros.""",
      "2":
          """O ciclo de vida é marcado por uma fase de extrema sensibilidade na primeira infância, que ocorre principalmente nos primeiros sete anos de vida. Neste período, a criança pode ser muito mimada ou superprotegida por uma figura feminina de destaque, como uma avó, devido à falta de segurança emocional maternal no ambiente familiar. Não se trata necessariamente da ausência da mãe, mas sim de como a criança interpreta emocionalmente a dinâmica familiar. Durante a adolescência, essa sensibilidade pode se manifestar em inseguranças que moldam a sua personalidade, levando-a a buscar apoio em relacionamentos precoces. Já na juventude, a oportunidade de desenvolver e fortalecer laços afetivos surge por meio das amizades e relacionamentos, porém, há o risco de se colocar em posições de submissão prejudiciais.""",
      "3":
          """A primeira infancia estágio da vida é marcado por uma infância vivida de maneira satisfatória, na qual a criança tem espaço para desenvolver seus talentos criativos; as brincadeiras e amizades serão essenciais nesse contexto. A experiência emocional dentro da família colabora para uma visão abrangente do conceito de família. Embora o período possa dificultar os estudos devido à distração, oferece muitas oportunidades para expressar as emoções através das diversas formas de arte. Na adolescência, a alegria de viver e a popularidade entre os amigos predominam. O período pode ser desfavorável aos estudos devido à dispersão, porém, com muitas oportunidades de expressar as emoções por meio das diversas formas de arte. Na juventude, as diversas oportunidades de relacionamento, as amizades e a popularidade, podem se tornar obstáculos para se comprometer com um relacionamento sério ou casamento. Por outro lado, esse será um momento da vida propício para as melhores expressões criativas em um período ainda de formação.""",
      "4":
          """O início do ciclo de vida  traz uma experiência emocional para a criança, do nascimento até os 14 anos, dentro do ambiente familiar, com a presença de uma figura masculina autoritária. Essa figura pode ser um pai rígido, controlador ou super protetor, ou mesmo ser representada por outra pessoa. Durante essa fase, é comum a criança receber uma educação disciplinadora e ser ensinada a obedecer aos pais. Na adolescência, essa disciplina pode resultar em uma vida restrita ou na necessidade de trabalhar, seja por motivos financeiros ou por escolha própria. A rigidez pode limitar a expressão criativa, mas mesmo assim, não impede o desenvolvimento saudável e o desejo de contribuir para sociedade. Quando chega a juventude, a personalidade moldada pela disciplina e rigidez ajuda a lidar com desafios e restrições que surgem. Isso pode ser um aspecto positivo para o crescimento profissional, porém pode dificultar a expressão criativa; tudo depende de como o caráter foi formado durante a infância e adolescência.""",
      "5":
          """O início do ciclo de vida 5 revela uma experiência emotiva intensa para a criança, na qual o excesso de liberdade pode despertar sentimentos de solidão. A ausência de uma disciplina educacional firme por parte dos pais pode levar a uma futura fragilidade na personalidade. Durante a adolescência, existe o perigo de se envolver em atividades ilegais ou vícios de natureza diversa. A falta de disciplina parental pode gerar a necessidade de buscar fora de casa o que não foi fornecido, sendo que nem sempre as opções disponíveis são positivas. Isso pode resultar em rebeldia ou falta de determinação durante a juventude. A maneira como a liberdade é direcionada no crescimento emocional pode ser determinante para o sucesso profissional e para a qualidade de vida em geral. Caso não seja bem direcionada, pode causar instabilidade e mudanças constantes. Apesar dos desafios, é possível superar os obstáculos.""",
      "6":
          """ciclo de vida 6 indica uma experiencia emocional, para a criança dentro do cenário familiar, no qual a sua percepção é a de se ver sob a necessidade de assumir responsabilidades e deveres muito cedo, quer seja por necessidade ou por iniciativa própria em face desse sentimento. Pode ser que desperte logo cedo um sentimento de culpa, inconsciente, que faz com que a criança se sinta obrigada a querer ajudar os pais e os irmãos.
Na adolescência, pode despertar o romantismo e uma possível busca por um relacionamento que pode levar ao casamento muito cedo, porquanto haja essa pressão do sentimento familiar, assim como pode ocorrer um direcionamento para participar de grupos sociais ou organizações que defendam a vida, os direitos humanos e o meio ambiente.
Na juventude, o cenário tenderá a se ampliar para a responsabilidade social, repercutindo de maneira bastante acentuada na carreira profissional. As relações humanas estarão na pauta durante todo o ciclo.""",
      "7":
          """O ciclo inicial da vida  revela uma experiência emocional significativa para a criança no ambiente familiar, onde sentimentos de solidão, falta de compreensão e retraimento podem ocorrer, tornando essa fase desafiadora. Essa vivência também pode refletir um ambiente familiar com forte influência intelectual, religiosa ou espiritual. Durante esse período, a criança demonstra introspecção e interesse por estudos. Na adolescência, é possível que surjam complexos de culpa e inseguranças que podem afetar o desenvolvimento da personalidade e a escolha de um caminho profissional, dependendo de suas experiências emocionais durante a infância e início da adolescência. Apesar disso, esse momento pode ser caracterizado por ela naturalmente  buscar  os estudos, visando obter uma sólida formação voltada para sua vocação. Na juventude, a introspecção e o interesse pelos estudos continuam, mas com novos desafios.""",
      "8":
          """Esse ciclo de vida representa uma vivência emocional intensa para a criança dentro da sua família, com muitas oportunidades para o seu desenvolvimento intelectual e educacional. No entanto, essa fase é desafiadora devido ao elevado nível de comprometimento que surge desde cedo nos sentimentos da criança. Logo na segunda infância, entre os 7 e os 14 anos de idade, já se desperta um senso de responsabilidade, preparando-a para a adolescência. Nesta fase, a busca pela afirmação pessoal e pela definição vocacional destaca-se, moldando a sua personalidade com a determinação de progredir intelectual e materialmente. A motivação será impulsionada por um forte senso ético e de justiça, mas se inclinar para o lado negativo, poderá recorrer a astúcia para atingir os seus objetivos, cometendo injustiças. Na juventude, é essencial equilibrar a ambição com a ética e a justiça, evitando assim cair na ganância por poder e riquezas materiais, desconsiderando princípios éticos em busca de status social elevado. Manter um equilíbrio entre os vários aspectos da vida é fundamental.
""",
      "9":
          """O início do ciclo de vida 9 pode representar uma experiência emocional intensa para a criança no ambiente familiar, trazendo desafios complexos e difíceis, com sentimentos de incompreensão, solidão e isolamento. Em alguns casos, a criança pode sentir uma responsabilidade exagerada, principalmente em relação aos irmãos, se os tiver. Contudo, esse período pode ser favorável para os estudos. Durante a adolescência, a sensibilidade aumentada, a dispersão e a sensação de não se encaixar podem se refletir nas relações sociais, prejudicando o desenvolvimento saudável das mesmas. É importante evitar o isolamento nessa fase, pois pode impactar negativamente as interações sociais. Por outro lado, a adolescência pode abrir portas para o desenvolvimento de talentos especiais e o aprimoramento acadêmico. Já na juventude, a falta de compreensão em relação às circunstâncias vividas pode gerar obstáculos no crescimento profissional e nas relações interpessoais. No entanto, esse período também traz oportunidades de crescimento emocional e autoconhecimento, essenciais para a maturidade e para uma vida futura mais bem-sucedida
""",
      "11":
          """O início do ciclo apresenta um quadro complexo no ambiente emocional da criança dentro da família. Sentimentos de exclusão, inspiração e despertar espiritual surgem precocemente. Em geral, durante a primeira infância, entre o nascimento e os 7 anos de idade, é comum a presença de uma figura feminina protetora que complementa a educação, frequentemente uma das avós. Na adolescência, o sentimento de exclusão se acentua no contexto social, podendo resultar em isolamento e dificuldade nos relacionamentos. A sensibilidade cresce e pode causar inseguranças consideráveis. A dificuldade em se inserir na sociedade pode levar a sensações de ser um estranho. No entanto, ao mesmo tempo, essa fase pode ser crucial para a construção da base que fortalecerá a personalidade. Na juventude, as aventuras podem resultar em desequilíbrios devido à intensidade das experiências emocionais, exigindo constante vigilância e foco até se alcançar o autocontrole na idade adulta. Muitos sonhos, ideais e ambições estão presentes nessa fase da vida.""",
    };
  }
}
